insert into accommodationamenitites (amenitie) values ("air conditioning");
insert into accommodationamenitites (amenitie) values ("hair dryer");
insert into accommodationamenitites (amenitie) values ("iron");
insert into accommodationamenitites (amenitie) values ("Dryer");
insert into accommodationamenitites (amenitie) values ("TV");
insert into accommodationamenitites (amenitie) values ("Indoor fireplace");
insert into accommodationamenitites (amenitie) values ("private entrance");
insert into accommodationamenitites (amenitie) values ("kitchen");
insert into accommodationamenitites (amenitie) values ("Heating");
insert into accommodationamenitites (amenitie) values ("Hangers");
insert into accommodationamenitites (amenitie) values ("washer");
insert into accommodationamenitites (amenitie) values ("hot water");
insert into accommodationamenitites (amenitie) values ("cable tv");
insert into accommodationamenitites (amenitie) values ("private bathroom");
insert into accommodationamenitites (amenitie) values ("private living room");
insert into accommodationamenitites (amenitie) values ("Wifi");
insert into accommodationamenitites (amenitie) values ("Self check-in");
insert into accommodationamenitites (amenitie) values ("free parking");
insert into accommodationamenitites (amenitie) values ("Laptop-friendly workspaces");
insert into accommodationamenitites (amenitie) values ("Instant Book");
select*from accommodationamenitites;