insert into cities (city_name,country_id) values ("Milwaukee",7);
insert into cities (city_name,country_id) values ("Bilbao",2);
insert into cities (city_name,country_id) values ("Buriram",3);
insert into cities (city_name,country_id) values ("Sunbury",4);
insert into cities (city_name,country_id) values ("Xi’an",6);
insert into cities (city_name,country_id) values ("Eugene",7);
insert into cities (city_name,country_id) values ("Luxembourg",8);
insert into cities (city_name,country_id) values ("Bucharest",5);
insert into cities (city_name,country_id) values ("Guadalajara",9);
insert into cities (city_name,country_id) values ("Efate",10);
insert into cities (city_name,country_id) values ("Cali",11);
insert into cities (city_name,country_id) values ("Cape Canaveral",7);
insert into cities (city_name,country_id) values ("Aberdeen",12);
insert into cities (city_name,country_id) values ("Courtenay",13);
insert into cities (city_name,country_id) values ("Ubatuba",14);
insert into cities (city_name,country_id) values ("Les Contamines-Montjoie",15);
insert into cities (city_name,country_id) values ("Tokyo",16);
insert into cities (city_name,country_id) values ("Kerala",17);
insert into cities (city_name,country_id) values ("Malindi",18);
insert into cities (city_name,country_id) values ("Maastricht",1);
select*from cities;