insert into countries (country_code,country_name) values ("NLD","Netherlands");
insert into countries (country_code,country_name) values ("ESP","Spain");
insert into countries (country_code,country_name) values ("THA","Thailand");
insert into countries (country_code,country_name) values ("AUS","Australia");
insert into countries (country_code,country_name) values ("ROU","Romania");
insert into countries (country_code,country_name) values ("CHN","China");
insert into countries (country_code,country_name) values ("USA","United States of America");
insert into countries (country_code,country_name) values ("LUX","Luxembourg");
insert into countries (country_code,country_name) values ("MEX","Mexico");
insert into countries (country_code,country_name) values ("VUT","Vanuatu");
insert into countries (country_code,country_name) values ("COL","Colombia");
insert into countries (country_code,country_name) values ("SCO","Scotland");
insert into countries (country_code,country_name) values ("CAN","Canada");
insert into countries (country_code,country_name) values ("BRA","Brazil");
insert into countries (country_code,country_name) values ("FRA","France");
insert into countries (country_code,country_name) values ("JPN","Japan");
insert into countries (country_code,country_name) values ("IND","India");
insert into countries (country_code,country_name) values ("KEN","Kenya");
insert into countries (country_code,country_name) values ("DEU","Germany");
insert into countries (country_code,country_name) values ("BEL","Belgium");
select*from countries;
